### ISSUE TITLE
NotImplementedError: Data must be downloaded manually and stored in the/workspaces/RadarGNN/data/nuscenes/raw folder!

### ISSUE THREAD

**Issue by Ainecop** [TUMFTM/RadarGNN#1]
The above is occuring due to following code in RadarGNN/src/gnnradarobjectdetection/create_dataset.py
   ```
 @property
    def raw_file_names(self):
        # no download of the raw dataset if this file is found in "root/raw" folder
        file_list = ['License.md']
        return file_list

    @property
    def processed_file_names(self):
        # no download if this file is found in "root/processed" folder
        file_list = ['config.json']
        return file_list 
```

**Q. Where can i get License.md as I am using v1.0-mini of nuscenes ?**

**Q. How can i create config.json? when it does not exist?**
  ** If possible share the files as well and please provide a folder structure for the nuscenes dataset you placed in directory named "raw".**

**Comment by ffent** [comment]
Hi @Ainecop, 
thanks for your interest in this topic and your questions regarding RadarGNN.

Q. Where can i get License.md as I am using v1.0-mini of nuscenes ?
A. The License.md file should be included in the files of the overall nuScenes dataset. However, if you don't have it, you can just create an arbitrary file with this name and no content.

Q. How can i create config.json? when it does not exist?
A. You don't have to create it yourself, but it will be created by the pre-processing pipeline. See: https://github.com/TUMFTM/RadarGNN/blob/main/src/gnnradarobjectdetection/preprocessor/nuscenes/dataset_creation.py#L372

The folder structure for the nuScenes dataset should look something like this:
```
.
|  
+---data/  
|   |  
|   +---datasets/  
|   |   |  
|   |   +---nuscenes/  
|   |   |   |
|   |   |   +---raw/                
|   |   |   |   |
|   |   |   |   +---License.md
|   |   |   |   |
|   |   |   |   +---v1.0-mini/
|   |   |   |   |
|   |   |   |   +---samples/
|   |   |   |   |
|   |   |   |   +---sweeps/
|   |
|   +---results/  
| 
+---docs/
|
+---configurations/
|   
+---test/
|
+---src/  
|
+---...
```
