### ISSUE TITLE
Viz of prediction model

### ISSUE THREAD

**Issue by abhigoku10** [TUMFTM/RadarGNN#2]
@TUMFTM @ffent  THanks for sharing the code base, wonderful work !!!, can you let us knw how to visual the predicted model results 
![image](https://github.com/TUMFTM/RadarGNN/assets/22094053/9de508b6-d657-44b9-aaf5-22329057cea4)

Thanks in advvance

**Comment by ffent** [comment]
Hi @abhigoku10, first of all, thanks for your interest in our work. 

Unfortunately, the visualization of the segmented image data is not part of the provided code base, but the figure (as shown in the publication) is a composition of different visualizations. However, the visualization of the radar point cloud and the associated object bounding boxes is possible by using the following methods:

https://github.com/TUMFTM/RadarGNN/blob/main/src/gnnradarobjectdetection/postprocessor/visualization.py
