### ISSUE TITLE
could not use nuScenes for this

### ISSUE THREAD

**Issue by ty1kotoba** [TUMFTM/RadarGNN#4]
@ffent @TUMFTM 
Hi 
currently I'm running this code in colab.
in the step of graph transfering
![image](https://github.com/TUMFTM/RadarGNN/assets/166467471/eec9d879-c634-4ba8-bcff-8754723a2290)
I'm new to torch-geometric so I'm not sure how to fix this. 

By the way, the radar_scenes wheel can not be  set up.  So I install it from git hub and remove the version restirction in setup.py.

**Comment by ty1kotoba** [comment]
![image](https://github.com/TUMFTM/RadarGNN/assets/166467471/35a42d3a-a78f-4ec9-996b-2f63404b00ac)

**Comment by ty1kotoba** [comment]
![image](https://github.com/TUMFTM/RadarGNN/assets/166467471/250a59c8-45fb-46e8-803a-fbd6a3ac22b0)
I set up the env on this version.

**Comment by ty1kotoba** [comment]
Could you add a forlder structure for nuScenes.

**Comment by ffent** [comment]
Hi @ty1kotoba, 
first of all, thanks for your interest in our work. This error normally occurs if the data is not available or is available but has a different structure. The required structure for the nuScenes dataset is similar to the RadarScenes structure and should look something like this:

<details>
<summary>Folder structure </summary>

```
.
|  
+---data/  
|   |  
|   +---datasets/  
|   |   |  
|   |   +---radarscenes/  
|   |   |   |
|   |   |   +---raw/                
|   |   |   |   |
|   |   |   |   +---License.md
|   |   |   |   |
|   |   |   |   +---data/        
|   |   |  
|   |   +---nuscenes/  
|   |   |   |
|   |   |   +---raw/                
|   |   |   |   |
|   |   |   |   +---License.md
|   |   |   |   |
|   |   |   |   +---maps/
|   |   |   |   |
|   |   |   |   +---samples/
|   |   |   |   |
|   |   |   |   +---sweeps/
|   |   |   |   |
|   |   |   |   +---v1.0-trainval/
|   |   |   |   |
|   |   |   |   +---...
|   |
|   +---results/  
| 
+---docs/
|
+---configurations/
|   
+---test/
|
+---src/  
|
+---...
```

</details>
<be>

Please note that the `nuscenes/raw/` folder has to include a `License.md` file. Sometimes, this is not part of the downloaded data but has to be added manually.

**Comment by ffent** [comment]
Please also have a look at #1

**Comment by ty1kotoba** [comment]
@ffent  Finally It works.  Thanks!
![image](https://github.com/TUMFTM/RadarGNN/assets/166467471/39ec5170-fea0-49d4-8ce0-3ab28eb5ad49)
while using the nuscenes, this code in typing.py is checking a file in the folder path root/....../raw/License.md

mean while the nuscenes dataset contain the license with out the **file suffix name  .md**
